### ISSUE TITLE
protective stop with ros_control

### ISSUE THREAD

**Issue by jacknlliu** [jacknlliu/ur_modern_driver#2]
firmware version: 3.3.4.310

```sh
[ERROR] [1547003438.325407105]: Robot is protective stopped!
[ERROR] [1547003438.325648688]: Aborting trajectory
[ERROR] [1547003438.325766930]: You are attempting to call methods on an uninitialized goal handle
[ERROR] [1547003441.533589773]: Robot is protective stopped!
[ERROR] [1547003704.125501149]: Robot is protective stopped!
[ERROR] [1547015232.648165078]: Robot is protective stopped!
[ERROR] [1547015244.328869971]: Unexpected error: No trajectory defined at current time. Please contact the package maintainer.
[ERROR] [1547015245.329841693]: Unexpected error: No trajectory defined at current time. Please contact the package maintainer.
[ERROR] [1547015249.886892405]: Robot is protective stopped!
[ERROR] [1547015251.390293340]: Robot is protective stopped!
[ERROR] [1547015254.838960305]: Unexpected error: No trajectory defined at current time. Please contact the package maintainer.
[ERROR] [1547015257.905876416]: Robot is protective stopped!
```
![screenshot from 2019-01-09 16-05-50](https://user-images.githubusercontent.com/6220143/50885678-58f24d80-1429-11e9-9693-180d1333bde9.png)

## Reference
- https://github.com/ros-industrial/ur_modern_driver/issues/105
- [Failure due to protective stop on the UR #54](https://github.com/ros-industrial/ur_modern_driver/issues/54)
- [UR5 arm is protective stopped during execution without touching any obstacles #384](https://github.com/ros-industrial/universal_robot/issues/384)
- https://github.com/ros-industrial/ur_modern_driver/issues/45
- https://github.com/ros-industrial/ur_modern_driver/pull/99
- [You are attempting to call methods on an uninitialized goal handle](https://answers.ros.org/question/266887/you-are-attempting-to-call-methods-on-an-uninitialized-goal-handle/)

**Comment by jacknlliu** [comment]
```sh
Unexpected error: No trajectory defined at current time
```

`rqt` can't get valid data.

## Reference
- [Unexpected error: No trajectory defined at current time](https://github.com/ros-industrial/ur_modern_driver/pull/120#issuecomment-431496779)
- [Velocity streaming #218](https://github.com/ros-industrial/ur_modern_driver/issues/218)
- [Issue with sample logic for joint_trajectory_controller in trajectory_interface.h #143](https://github.com/ros-controls/ros_controllers/issues/143)

**Comment by jacknlliu** [comment]
Possible issues:
- communication error
	- the protocol is different in firmware version 3.3.4.310, such as pack size?
		- The pack size is less than 2048.
	- `/joint_states` and `hardware interface` in ros control can't get valid data(data jumping) after a few minutes, sometimes we get `no messages` from `rostopic hz /joint_states`, and only 1 Hz for joint states! **Maybe unpack error for v3.3?**
- position control issue
	- acceleration and vel limits are not the same as the real robot settings
- position controller based on vel interface
	- PID parameters for vel which may cause the joint speed out of the limit
    - incorrect acceleration setting from the joint trajectory controller to ur hardware interface(`speedj()`),see [here](https://github.com/ros-industrial/universal_robot/issues/384#issuecomment-433614768).
- mechanical failure
	- joint position deviation from the designed model

**Comment by jacknlliu** [comment]
rqt_joint_trajectory_controller:
```sh
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_joint_trajectory_controller/joint_trajectory_controller.py", line 428, in _update_cmd_cb
    self._cmd_pub.publish(traj)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 886, in publish
    raise ROSSerializationException(str(e))
rospy.exceptions.ROSSerializationException: <class 'struct.error'>: 'integer out of range for 'i' format code' when writing '10136431958073778304385650838915089352497362729450656266185768343912164969068343814491130656221911512084591072349657775418879218483551627682630900033986257069101061831707756387901440815160610564564863428031676416000000000'
```

**Comment by jacknlliu** [comment]
I find that UR robot with firmware 3.3.4.310 can't get stable communication with 125Hz, UR can't parse the script commands from TCP packages correctly(especially in velocity mode), and this also makes the wrong robot state msgs from UR to host, then it will make the ros control loop broken.

Possible issues in UR:
- TCP sticky package problem in UR controller. Maybe lack some check about integrality of the TCP package. We know that the URscript tcp package is variable length package!
	- [x] print the `speedj` command will that speed of joint is OK(no data jumping)! So command from host to UR controller is OK.
    - [ ] The pack size using `recv` is 1060 < 2048, and the deserialization is OK, so state protocol from UR to host is also OK. But maybe the wrong TCP communication from UR to host.
	- [ ] mechanical failure

**Solution:**
- using the trajectory follower interface without ros control
- or set the ros control loop as 30Hz or upgrade UR controller firmware(only the latest v3.8.0.61336 works!).
- modify the hardware interface default acceleration for joint trajectory controller
- set appropriate control frequency for controller
